# Workflow name
name: Deploy theme to live
 
on:
  # Run automatically on push to main branch
  push:
    branches: [ main ]
    paths:
    - 'src/**'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get files
      uses: actions/checkout@v2.3.4
      
    - name: FTP Deploy
      uses: cinderblockgames/ftp-action@v1.2.2
      with:
        # required
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        # optional
        port: 21
        dry-run: true
        source: src/path
        destination: public_html/wp-content/themes/shal3v-1
        skipUnchanged: true
        skipDirectories: .github|.well-known|configs|private-keys
        test: true
